In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("DateFruit_Dataset.csv")

In [3]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

### EDA

In [4]:
df.describe()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
count,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,...,898.000000,898.000000,898.000000,898.000000,8.980000e+02,8.980000e+02,8.980000e+02,898.000000,898.000000,898.000000
mean,298295.207127,2057.660953,750.811994,495.872785,0.737468,604.577938,0.981840,303845.592428,0.736267,2.131102,...,0.250518,4.247845,5.110894,3.780928,-3.185021e+10,-2.901860e+10,-2.771876e+10,50.082888,48.805681,48.098393
std,107245.205337,410.012459,144.059326,114.268917,0.088727,119.593888,0.018157,108815.656947,0.053745,17.820778,...,0.632918,2.892357,3.745463,2.049831,2.037241e+10,1.712952e+10,1.484137e+10,16.063125,14.125911,10.813862
min,1987.000000,911.828000,336.722700,2.283200,0.344800,50.298400,0.836600,2257.000000,0.512300,1.065300,...,-1.029100,1.708200,1.607600,1.767200,-1.091224e+11,-9.261697e+10,-8.747177e+10,15.191100,20.524700,22.130000
25%,206948.000000,1726.091500,641.068650,404.684375,0.685625,513.317075,0.978825,210022.750000,0.705875,1.373725,...,-0.196950,2.536625,2.508850,2.577275,-4.429444e+10,-3.894638e+10,-3.564534e+10,38.224425,38.654525,39.250725
50%,319833.000000,2196.345450,791.363400,495.054850,0.754700,638.140950,0.987300,327207.000000,0.746950,1.524150,...,0.135550,3.069800,3.127800,3.080700,-2.826156e+10,-2.620990e+10,-2.392928e+10,53.841300,50.337800,49.614100
75%,382573.000000,2389.716575,858.633750,589.031700,0.802150,697.930525,0.991800,388804.000000,0.775850,1.674750,...,0.593950,4.449850,7.320400,4.283125,-1.460482e+10,-1.433105e+10,-1.660367e+10,63.063350,59.573600,56.666675
max,546063.000000,2811.997100,1222.723000,766.453600,1.000000,833.827900,0.997400,552598.000000,0.856200,535.525700,...,3.092300,26.171100,26.736700,32.249500,-1.627316e+08,-5.627727e+08,-4.370435e+08,79.828900,83.064900,74.104600

In [5]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [7]:
df.columns

Index(['AREA', 'PERIMETER', 'MAJOR_AXIS', 'MINOR_AXIS', 'ECCENTRICITY',
       'EQDIASQ', 'SOLIDITY', 'CONVEX_AREA', 'EXTENT', 'ASPECT_RATIO',
       'ROUNDNESS', 'COMPACTNESS', 'SHAPEFACTOR_1', 'SHAPEFACTOR_2',
       'SHAPEFACTOR_3', 'SHAPEFACTOR_4', 'MeanRR', 'MeanRG', 'MeanRB',
       'StdDevRR', 'StdDevRG', 'StdDevRB', 'SkewRR', 'SkewRG', 'SkewRB',
       'KurtosisRR', 'KurtosisRG', 'KurtosisRB', 'EntropyRR', 'EntropyRG',
       'EntropyRB', 'ALLdaub4RR', 'ALLdaub4RG', 'ALLdaub4RB', 'Class'],
      dtype='object')

In [8]:
df.shape

(898, 35)

In [11]:
X = df.drop("Class" , axis=1)
y = df["Class"]

In [12]:
df["Class"].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [13]:
X.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666

In [14]:
y.head()

0    BERHI
1    BERHI
2    BERHI
3    BERHI
4    BERHI
Name: Class, dtype: object

In [15]:
X.shape

(898, 34)

In [20]:
from sklearn.preprocessing import StandardScaler , LabelEncoder 
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [25]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X, y , test_size=0.2 , random_state=42)

In [30]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ANN

In [53]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader , TensorDataset

In [54]:
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)

X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [55]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

#### Create DataLoader

In [56]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)

### Build our Model

In [66]:
# class ANN(nn.Module):
#     def __init__(self):
#         super(ANN, self).__init__()
#         self.model = nn.Sequential(
#             nn.Linear(X_train_tensor.shape[1], 64),
#             nn.ReLU(),
#             nn.Linear(64, 64),
#             nn.ReLU(),
#             nn.Linear(64, 7)
#         )
        
#         def forward(self, x):
#             return self.model(x)

class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(X_train_tensor.shape[1], 64),
            nn.ReLU(),
            nn.Linear(64, 7)
        )

    def forward(self, x):   # ✅ must be inside class
        return self.model(x)

In [67]:
model = ANN()

# loss & Optimer 

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

#### Training the Neural Network

In [68]:
epochs = 100 


for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    
    for xb, yb in train_loader:
        optimizer.zero_grad()
        
        outputs = model(xb)
        loss = criterion(outputs, yb)   # fixed
        
        loss.backward()
        optimizer.step()

        running_loss += loss.item()   # fixed

    train_loss = running_loss / len(train_loader)
    
    print(f'Epoch = {epoch+1}/{epochs}, Loss = {train_loss}')

Epoch = 1/100, Loss = 1.7372145030809485
Epoch = 2/100, Loss = 1.1952659669129744
Epoch = 3/100, Loss = 0.8618975126225016
Epoch = 4/100, Loss = 0.6822338687336963
Epoch = 5/100, Loss = 0.5823851849721826
Epoch = 6/100, Loss = 0.5202331076497617
Epoch = 7/100, Loss = 0.4625682960385862
Epoch = 8/100, Loss = 0.42771863548651984
Epoch = 9/100, Loss = 0.40151994902154675
Epoch = 10/100, Loss = 0.3725649397010389
Epoch = 11/100, Loss = 0.34754395549711975
Epoch = 12/100, Loss = 0.32866998859073804
Epoch = 13/100, Loss = 0.30878137246422144
Epoch = 14/100, Loss = 0.29450594925362134
Epoch = 15/100, Loss = 0.276704053192035
Epoch = 16/100, Loss = 0.27056749165058136
Epoch = 17/100, Loss = 0.26632953856302344
Epoch = 18/100, Loss = 0.24822311103343964
Epoch = 19/100, Loss = 0.24158579175886902
Epoch = 20/100, Loss = 0.23058943968752157
Epoch = 21/100, Loss = 0.22306715988594553
Epoch = 22/100, Loss = 0.21955170288034107
Epoch = 23/100, Loss = 0.21193805887647296
Epoch = 24/100, Loss = 0.20903957116863
Epoch = 25/100, Loss = 0.20159224355998245
Epoch = 26/100, Loss = 0.19087976120088412
Epoch = 27/100, Loss = 0.18921452663514926
Epoch = 28/100, Loss = 0.188441708036091
Epoch = 29/100, Loss = 0.1790803023006605
Epoch = 30/100, Loss = 0.1824526521174804
Epoch = 31/100, Loss = 0.18126463663318884
Epoch = 32/100, Loss = 0.17296914270390634
Epoch = 33/100, Loss = 0.16445800046557965
Epoch = 34/100, Loss = 0.16390140694768532
Epoch = 35/100, Loss = 0.16027161511390106
Epoch = 36/100, Loss = 0.16426351310118384
Epoch = 37/100, Loss = 0.15263138484695685
Epoch = 38/100, Loss = 0.15200815349817276
Epoch = 39/100, Loss = 0.1481697386049706
Epoch = 40/100, Loss = 0.1498992454422557
Epoch = 41/100, Loss = 0.14877402555683386
Epoch = 42/100, Loss = 0.14524943268169527
Epoch = 43/100, Loss = 0.1430032765087874
Epoch = 44/100, Loss = 0.14239745165990747
Epoch = 45/100, Loss = 0.14053862396141756
Epoch = 46/100, Loss = 0.13527373337875243
Epoch = 47/100, Loss = 0.13216481511683567
Epoch = 48/100, Loss = 0.1293640288969745
Epoch = 49/100, Loss = 0.13318824703278748
Epoch = 50/100, Loss = 0.1326776942157227
Epoch = 51/100, Loss = 0.1255388676148394
Epoch = 52/100, Loss = 0.125296410497116
Epoch = 53/100, Loss = 0.12104633288538974
Epoch = 54/100, Loss = 0.12199267380587432
Epoch = 55/100, Loss = 0.11799382155194231
Epoch = 56/100, Loss = 0.11962861826886302
Epoch = 57/100, Loss = 0.12160656844144282
Epoch = 58/100, Loss = 0.11593597560473111
Epoch = 59/100, Loss = 0.11568345534412758
Epoch = 60/100, Loss = 0.11304027846326
Epoch = 61/100, Loss = 0.11129086537529594
Epoch = 62/100, Loss = 0.1104708627352248
Epoch = 63/100, Loss = 0.1123359352350235
Epoch = 64/100, Loss = 0.11258507811504861
Epoch = 65/100, Loss = 0.10680274001282195
Epoch = 66/100, Loss = 0.10961047219841377
Epoch = 67/100, Loss = 0.10472661629319191
Epoch = 68/100, Loss = 0.102085095870754
Epoch = 69/100, Loss = 0.10193039039554803
Epoch = 70/100, Loss = 0.10395073599141577
Epoch = 71/100, Loss = 0.10788878102017485
Epoch = 72/100, Loss = 0.1008817890416021
Epoch = 73/100, Loss = 0.09943186880453773
Epoch = 74/100, Loss = 0.09735612846587015
Epoch = 75/100, Loss = 0.09673669545546822
Epoch = 76/100, Loss = 0.09568154390739358
Epoch = 77/100, Loss = 0.09588628262281418
Epoch = 78/100, Loss = 0.09333925090892159
Epoch = 79/100, Loss = 0.09367747633191555
Epoch = 80/100, Loss = 0.09936435326285985
Epoch = 81/100, Loss = 0.09046211207042569
Epoch = 82/100, Loss = 0.0884268410179926
Epoch = 83/100, Loss = 0.09057385571624922
Epoch = 84/100, Loss = 0.08660760546184104
Epoch = 85/100, Loss = 0.08502477043024871
Epoch = 86/100, Loss = 0.08421384308325208
Epoch = 87/100, Loss = 0.08881958088149196
Epoch = 88/100, Loss = 0.08946668964041316
Epoch = 89/100, Loss = 0.08457308740395567
Epoch = 90/100, Loss = 0.08178716695503048
Epoch = 91/100, Loss = 0.0828603963246164
Epoch = 92/100, Loss = 0.080783283094997
Epoch = 93/100, Loss = 0.07897574223739945
Epoch = 94/100, Loss = 0.07911637198665868
Epoch = 95/100, Loss = 0.07950997522667698
Epoch = 96/100, Loss = 0.07954840953259365
Epoch = 97/100, Loss = 0.07814446002568888
Epoch = 98/100, Loss = 0.07780799075313237
Epoch = 99/100, Loss = 0.07490794384933036
Epoch = 100/100, Loss = 0.07365380235664222

In [69]:
# Evaluate

In [72]:
model.eval()
total = 0
correct = 0

with torch.no_grad():
    for xb , yb in test_loader:
        outputs = model(xb) # [0.2 , 0.4, -0.6]
        _, predicted = torch.max(outputs ,1)

        correct += (predicted == yb).sum().item()
        total += yb.size(0) # actual samples in each batch

print("total", total)
print("accuracy ",correct)

total 180
accuracy  175

In [71]:
y_test.shape

(180,)