### IMDB Data(Movie Review Data)

In [1]:
# 50,000 reviews

In [38]:
import numpy as np 
import pandas as pd

In [39]:
df = pd.read_csv("IMDB Dataset.csv")

In [40]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [41]:
df.shape

(50000, 2)

In [42]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [44]:
df.drop_duplicates(inplace=True)
df.shape

(49582, 2)

### Text Preproceesing

In [45]:
# What steps we are performs in this Projects

#covert to lowercase 
#remove URLS
# Remove HTML tags
# remove Stopwords
# Remove Punctuations (? > , # $ )
# Perform Steamming  
# Target value convert into num 
# Perform Vectorizations (TF - IDF) - covert text into Numbers

In [46]:
df['review'] = df['review'].str.lower()

In [47]:
# removing urls using regEx 
import re

def remove_urls(text):
    return re.sub(r"http\s+","",text)

df['review'] = df['review'].apply(remove_urls)

In [48]:
# removing punctuations 
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]","",text)
    return text

In [49]:
df['review'] = df['review'].apply(remove_punctuations)

In [28]:
# remove HTML Tags

In [51]:
def remove_html(text):
    text = re.sub(r"<.*?>","",text)
    return text
df['review'] = df['review'].apply(remove_html)

In [52]:
# Removing Stop Words

In [53]:
import nltk 
nltk.download("punkt")

nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Nikhil\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Nikhil\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [54]:
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords

In [58]:
# remove stop words 

def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text.replace(word , "")
    return text
df['review'] = df['review'].apply(remove_stopwords)

In [59]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [60]:
from nltk.stem import PorterStemmer 

def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)
    return " ".join(stemmed_words)
df['review'] = df['review'].apply(stemming)

In [61]:
### Encoding

In [64]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["sentiment"] = le.fit_transform(df["sentiment"])

In [65]:
y = df["sentiment"]
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int32

In [66]:
# Vectorization tf-idf 
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=5000)
X = tf.fit_transform(df["review"])

In [68]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5871087 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3123)	0.02032251735685024
  (0, 3098)	0.09542098470744526
  (0, 4441)	0.20903467205715237
  (0, 3152)	0.057164905655617715
  (0, 3690)	0.04795018941759714
  (0, 2025)	0.024837126680226217
  (0, 2810)	0.05093623457657249
  (0, 4439)	0.06274954229236089
  (0, 163)	0.032260181258981106
  (0, 4821)	0.07851591273828991
  (0, 2476)	0.04850405470299644
  (0, 3185)	0.43216782713328356
  (0, 1535)	0.10274122058172444
  (0, 4987)	0.05287089753313154
  (0, 443)	0.05711365014241208
  (0, 2179)	0.07161368973329611
  (0, 4456)	0.024446041394784856
  (0, 301)	0.041296577361905513
  (0, 3713)	0.08249984253761973
  (0, 324)	0.07507443472841555
  (0, 4461)	0.04274859304710011
  (0, 2387)	0.1295866356729789
  (0, 1583)	0.05594527309388424
  (0, 4864)	0.049933268194460693
  (0, 2053)	0.04118502050404425
  :	:
  (49581, 2286)	0.09370049477083149
  (49581, 1655)	0.16515065743591884
  (49581, 2207)	0.0807050171213464
  (49581, 4604)	0.09124520635183705
  (49581, 776)	0.10606814986101117
  (49581, 3829)	0.0969614002395767
  (49581, 2524)	0.10984319095358464
  (49581, 4660)	0.0994442296449171
  (49581, 2586)	0.09254382643575335
  (49581, 2354)	0.13974759078626203
  (49581, 379)	0.11062351220232874
  (49581, 2061)	0.12366306939993575
  (49581, 3641)	0.10501109054108233
  (49581, 2267)	0.1603929003910312
  (49581, 318)	0.10474191443679787
  (49581, 4585)	0.1548917714869443
  (49581, 2512)	0.17800008244249405
  (49581, 4162)	0.1951942180887046
  (49581, 1088)	0.15522934182669346
  (49581, 682)	0.1432055922664932
  (49581, 3025)	0.15987763334791602
  (49581, 2943)	0.16869126598604967
  (49581, 778)	0.12541386082039135
  (49581, 1957)	0.1531895792131522
  (49581, 3642)	0.14696302897312627

In [69]:
 # DATA set And DataLoader

In [72]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(
    X , y ,test_size=0.2 , random_state=42
)

In [73]:
X_train.shape

(39665, 5000)

In [74]:
X_test.shape

(9917, 5000)

In [75]:
import torch 
from torch.utils.data import TensorDataset , DataLoader

In [76]:
X_train = X_train.toarray()
X_test = X_test.toarray()

In [77]:
train_set = TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)

test_set = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [78]:
train_loader = DataLoader(train_set , shuffle=True , batch_size=64)
test_loader = DataLoader(test_set , shuffle=True , batch_size=64)

# Build RNN

In [81]:
import torch
import torch.nn as nn
import torch.optim as optim

class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super(RNN, self).__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # RNN layer
        self.rnn = nn.RNN(
            input_size,
            hidden_size,
            num_layers,
            batch_first=True
        )

        # Fully connected layer
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        batch_size = x.size(0)

        h0 = torch.zeros(
            self.num_layers,
            batch_size,
            self.hidden_size
        ).to(x.device)   # important fix

        out, _ = self.rnn(x, h0)

        out = self.fc(out[:, -1, :])  # last timestep
        return out

In [82]:
input_size = X_train.shape[1]
model  = RNN(input_size)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

# Training the RNN

In [85]:
epochs = 10
for epoch in range(epochs):
    model.train()

    for Xb , yb in train_loader:
        optimizer.zero_grad()

        Xb = Xb.unsqueeze(1)

        outputs = model(Xb)  
        outputs = torch.sigmoid(outputs.squeeze())

        loss = criterion(outputs , yb)

        loss.backward()  
        optimizer.step()  # weights update

    print(f'epoch = {epoch+1}/{epoch} and loss = {loss.item()}')

epoch = 1/0 and loss = 0.1454802006483078
epoch = 2/1 and loss = 0.1794196367263794
epoch = 3/2 and loss = 0.28885897994041443
epoch = 4/3 and loss = 0.19149860739707947
epoch = 5/4 and loss = 0.11113691329956055
epoch = 6/5 and loss = 0.30455973744392395
epoch = 7/6 and loss = 0.39754778146743774
epoch = 8/7 and loss = 0.14048834145069122
epoch = 9/8 and loss = 0.20549792051315308
epoch = 10/9 and loss = 0.13820475339889526

In [87]:
model.eval()

with torch.no_grad():
    correct_vals = 0
    tot_vals = 0

    for Xb , yb in test_loader:
        Xb = Xb.unsqueeze(1)
        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()
        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

    print(f'accuracy = {correct_vals/tot_vals*100}')

accuracy = 87.21387516386004